"""Initial Migration

Revision ID: dabe71e28576
Revises: 
Create Date: 2025-03-21 01:13:01.808062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dabe71e28576'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Feedback',
    sa.Column('feedback_id', sa.String(), nullable=False),
    sa.Column('pain_level', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('feedback_id')
    )
    op.create_table('Physios',
    sa.Column('physio_id', sa.String(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('physio_id')
    )
    op.create_table('Roles',
    sa.Column('role_id', sa.String(), nullable=False),
    sa.Column('role_name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('Treatments',
    sa.Column('treatment_id', sa.String(), nullable=False),
    sa.Column('treatment_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('treatment_id')
    )
    op.create_table('Exercises',
    sa.Column('exercise_id', sa.String(), nullable=False),
    sa.Column('exercise_name', sa.String(length=255), nullable=False),
    sa.Column('equipment', sa.String(length=255), nullable=False),
    sa.Column('instructions', sa.String(length=255), nullable=False),
    sa.Column('video_link', sa.String(length=255), nullable=False),
    sa.Column('muscles_worked', sa.String(length=255), nullable=False),
    sa.Column('benefits', sa.String(length=255), nullable=False),
    sa.Column('image_link', sa.String(length=255), nullable=False),
    sa.Column('treatment_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['treatment_id'], ['Treatments.treatment_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('exercise_id')
    )
    op.create_table('Users',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['Roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('Appointments',
    sa.Column('appointment_id', sa.String(), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('appointment_type', sa.String(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('physio_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['physio_id'], ['Physios.physio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id')
    )
    op.create_table('Programs',
    sa.Column('program_id', sa.String(), nullable=False),
    sa.Column('program_name', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('num_days', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('physio_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['physio_id'], ['Physios.physio_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('program_id')
    )
    op.create_table('ExerciseSessions',
    sa.Column('exercise_session_id', sa.String(length=36), nullable=False),
    sa.Column('exercise_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('program_id', sa.String(length=36), nullable=False),
    sa.Column('date_time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['Exercises.exercise_id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['Programs.program_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['Users.user_id'], ),
    sa.PrimaryKeyConstraint('exercise_session_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ExerciseSessions')
    op.drop_table('Programs')
    op.drop_table('Appointments')
    op.drop_table('Users')
    op.drop_table('Exercises')
    op.drop_table('Treatments')
    op.drop_table('Roles')
    op.drop_table('Physios')
    op.drop_table('Feedback')
    # ### end Alembic commands ###
